### ISSUE TITLE
Why not AHCP?

### ISSUE THREAD

**Issue by mitar** [sudomesh/notdhcpserver#1]
http://www.pps.univ-paris-diderot.fr/~jch/software/ahcp/

**Comment by mitar** [comment]
Or https://github.com/sbyx/hnetd/

**Comment by Juul** [comment]
On Fri, Apr 17, 2015 at 2:13 AM, Mitar notifications@github.com wrote:

> Or https://github.com/sbyx/hnetd/

Thanks for the suggestions. This is only used for our extender nodes. From
the FAQ on nothdpc:
- Q: Why did you write this? Why not just use the dnsmasq dhcp server?
- A: The behaviour we want is very specific. nothdcpserver hands out
  only one IP per interface and does not keep track of lease time. Every time
  there is a physical disconnect on the interface the state is reset. dnsmasq
  uses the IP of each interface to decide which dhcp-range to hand out on
  that interface. This is problematic since we use the same IP on multiple
  non-bridged interfaces. We still use dnsmasq for normal DHCP. We are also
  handing out an SSL cert and key along with the IP. Lastly, we don't want to
  give these IPs out to anything that isn't an extender node and we want to
  run both notdhcpserver and dnsmasq dhcp server on the same interface at the
  same time such that the interface can work as an extra LAN port until an
  extender node is plugged in, at which time it will be switched over to
  become a dedicated extender node port.

## 

marc/juul
