### ISSUE TITLE
Run down hook script on SIGTERM or SIGHUP

### ISSUE THREAD

**Issue by Juul** [sudomesh/notdhcpserver#5]
Both server and client should run the down hook script when terminated assuming the state indicates that the up hook script had previously been run.

**Comment by max-b** [comment]
So I've got this implemented in fc4035ccac06f41e261a8919e74cfd78f409946b.

However, if one side of the notdhcp transaction quits, the other side doesn't know about it until there's a disconnect. So if the client were to restart the daemon, the server wouldn't reset to initial state and it'd be stuck again.

The simplest solution would be to bring the interface down and then back up, which would trigger the other side to run its down script.

I suppose we could also consider sending a special "reset" message...

**Comment by max-b** [comment]
I decided to go with a heartbeat/timeout approach.

We can't do the "interface down and then back up", because our code is only listening for physical link state changes. `ip link set eth0 down` doesn't actually trigger a link state change. I believe that nothing we can do on one end will trigger that link state change, except for unplugging the cord or powering off the router.

I implemented the heartbeat/timeout functionality in https://github.com/sudomesh/notdhcp/tree/timeouts and it's been merged to master. I'm going to do some more testing to the best of my availability and I will certainly report any issues here :)
